config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {
    invitations: 'users/invitations'
  }
  resources :users, only: :show
  
  resources :healths
  resources :pets
  resources :families
  resources :tasks
  
  root to: "healths#index"
  
  
  post '/tasks/:id/done' => 'tasks#done',   as: 'done'
  get 'search' => 'healths#search'

end

app/models/health.rb
class Health < ApplicationRecord
  belongs_to :user
  belongs_to :pet

  def self.search(keyword)
    where(["title like? OR content like?", "%#{keyword}%", "%#{keyword}%"])
  end
end

app/controllers/healths_controller.rb
class HealthsController < ApplicationController
  before_action :set_health, only: %i[ show edit update destroy ]
  before_action :set_pets, only: %i[ new create edit update ]

  # GET /healths or /healths.json
  def index
    @healths = Health.all.page(params[:page]).per(5)
  end

  # GET /healths/1 or /healths/1.json
  def show
  end

  # GET /healths/new
  def new
    @health = Health.new
  end

  # GET /healths/1/edit
  def edit
  end

  # POST /healths or /healths.json
  def create
    @health = Health.new(health_params)

    respond_to do |format|
      if @health.save
        format.html { redirect_to health_url(@health), notice: "Health was successfully created." }
        format.json { render :show, status: :created, location: @health }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @health.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /healths/1 or /healths/1.json
  def update
    respond_to do |format|
      if @health.update(health_params)
        format.html { redirect_to health_url(@health), notice: "Health was successfully updated." }
        format.json { render :show, status: :ok, location: @health }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @health.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /healths/1 or /healths/1.json
  def destroy
    @health.destroy

    respond_to do |format|
      format.html { redirect_to healths_url, notice: "Health was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    @healths = Health.search(params[:keyword]).page(params[:page]).per(20)
    @keyword = params[:keyword]
    render "index"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_health
      @health = Health.find(params[:id])
    end

    def set_pets
      @pets = current_user.families.first.pets
    end

    # Only allow a list of trusted parameters through.
    def health_params
      params.require(:health).permit(:user_id, :pet_id, :title, :content, :start_time)
    end
end

app/helpers/healths_helper.rb
module HealthsHelper
end

app/views/healths/_form.html.erb
<div class="col-3">
  <%= form_with(model: health) do |form| %>
    <% if health.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(health.errors.count, "error") %> prohibited this health from being saved:</h2>

        <ul>
          <% health.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :ペット名 %><br>
      <%= form.collection_select(:pet_id,@pets,:id,:name)%>
    </div>

    <div class="time">
      <div class="form-tag">日付</div>
      <%= form.datetime_select :start_time %>
    </div>

    <div class="field">
      <%= form.label :体調 %><br>
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <%= form.label :詳細 %><br>
      <%= form.text_area :content %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>

    <%= form.hidden_field :user_id, :value => current_user.id %>
  <% end %>
</div>

app/views/healths/edit.html.erb
<h1>Editing Health</h1>

<%= render 'form', health: @health %>

<%= link_to 'Show', @health %> |
<%= link_to 'Back', healths_path %>

app/views/healths/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>Healths</h1>
  <%= link_to 'New Health', new_health_path %>
  <hr />
  <div class="search-form">
    <%= form_with url: search_path, method: :get, local: true do |f| %>
      <%= f.text_field :keyword, value: @keyword %>
      <%= f.submit "検索" %>
    <% end %>
  </div>
  <hr />
  <div class="row">
    <div class ="col-md-4">
      <table>
        <thead>
          <tr>
            <th>状態</th>
            <th>日付</th>
            <th>愛犬</th>
            <th>担当</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @healths.each do |health| %>
            <% if health.pet.family.id == current_user.families.first.id %>
              <tr>
                <td><%= link_to health.title , health %></td>
                <td><%= health.start_time.strftime("%Y-%m-%d") %></td>
                <td><%= health.pet.name %></td>
                <td><%= health.user.name %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
      <br>
      <%= paginate @healths %>
    </div>
    <hr />
    <br><br>
    <%= month_calendar events: @healths do |date, healths| %>
      <%= date %>
      <div>
        <% healths.each do |health| %>
          <% if health.pet.family.id == current_user.families.first.id %>
            <%= link_to health.title, health %><br>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<br>

app/views/healths/new.html.erb
<h1>体調記録</h1>
<hr />
<%= render 'form', health: @health %>

<%= link_to 'Back', healths_path %>

app/views/healths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>担当:</strong><br>
  <%= @health.user.name %>
</p>

<p>
  <strong>愛犬:</strong><br>
  <%= @health.pet.name%>
</p>

<p>
  <strong>体調:</strong><br>
  <%= @health.title %>
</p>

<p>
  <strong>詳細:</strong><br>
  <%= @health.content %>
</p>
<%= link_to 'Destroy', @health, method: :delete, data: { confirm: 'Are you sure?' } %>|
<%= link_to 'Edit', edit_health_path(@health) %> |
<%= link_to 'Back', healths_path %>