config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {
    invitations: 'users/invitations'
  }
  resources :users, only: :show
  
  resources :healths
  resources :pets
  resources :families
  resources :tasks
  
  root to: "healths#index"
  
  
  post '/tasks/:id/done' => 'tasks#done',   as: 'done'
  get 'search' => 'healths#search'

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :pet
  belongs_to :user

  def self.today_tasks
    today_tasks = []
    Task.all.each do |task|
      if task.start_time.strftime("%Y-%m-%d") == Date.today.strftime("%Y-%m-%d")
        today_tasks << task
      end
    end
    today_tasks
  end

  def self.remind
    tasks = Task.where(mailer:false)
    tasks.each do |task|
      if task.start_time < Time.now
        TodoMailer.send_at_the_time(task.user,task).deliver
        task.mailer = true
        task.save
      end
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: %i[ show edit update destroy done]
  before_action :set_pets, only: %i[ new create edit update ]
  before_action :set_users, only: %i[ new create edit update ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.today_tasks
    @calendars = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def done
    if @task.update(is_done: true )
      DoneMailer.send_when_done(@task).deliver
      redirect_to tasks_path
    else 
      render 'index'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :content, :start_time, :pet_id, :user_id)
    end

    def set_pets
      @pets = current_user.families.first.pets
    end

    def set_users
      @users = current_user.families.first.users
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :ペット名 %><br>
    <%= form.collection_select(:pet_id,@pets,:id,:name)%>
  </div>

  <div class="field">
    <%= form.label :実行人 %><br>
    <%= form.collection_select(:user_id,@users,:id,:name)%>
  </div>

  <div class="field">
    <%= form.label :実行時間 %><br>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :タスク名 %><br>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :備考欄 %><br>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h2>タスク一覧</h2>
      <%= link_to 'New Task', new_task_path %>
      <hr />
      <br>
        <table>
          <thead>
            <tr>
              <th>Title</th>
              <th>Time</th>
              <th>User</th>
              <th>Pet</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @tasks.filter{|task| !task.is_done? }.each do |task| %>
              <% if task.pet.family.id == current_user.families.first.id %>
                <tr>
                  <td><%= link_to task.title , task %></td>
                  <td><%= task.start_time.strftime("%H:%M") %></td>
                  <td><%= task.user.name%></td>
                  <td><%= task.pet.name%></td>
                  <td><%= link_to 'Done', done_path(task.id), method: :post %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
    </div>
    <div class="col-md-6">
      <h2>完了</h2>
      <br>
      <hr />
      <table>
        <thead>
          <br>
          <tr>
            <th>Title</th>
            <th>User</th>
            <th>Pet</th>
          </tr>
        </thead>
        <tbody>
          <% @tasks.filter{|task| task.is_done? }.each do |task| %>
            <% if task.pet.family.id == current_user.families.first.id %>
              <tr>
                <td><%= link_to task.title , task %></td>
                <td><%= task.user.name%></td>
                <td><%= task.pet.name %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <br><br>
  <%= month_calendar events: @calendars do |date, tasks| %>
    <%= date %>
    <div>
      <% tasks.each do |task| %>
        <% if task.pet.family.id == current_user.families.first.id %>
          <%= link_to task.title, task %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/tasks/new.html.erb
<h1>タスク登録</h1>
<hr />
<div class="col-md-3">
    <%= render 'form', task: @task %>

    <%= link_to 'Back', tasks_path %>
</div>

app/views/tasks/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<p>
  <strong>Time:</strong>
  <%= @task.start_time %>
</p>

<%= link_to 'Back', tasks_path %> |
<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Destroy', @task, method: :delete, data: { confirm: 'Are you sure?' } %>