config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {
    invitations: 'users/invitations'
  }
  resources :users, only: :show
  
  resources :healths
  resources :pets
  resources :families
  resources :tasks
  
  root to: "healths#index"
  
  
  post '/tasks/:id/done' => 'tasks#done',   as: 'done'
  get 'search' => 'healths#search'

end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :family

  has_many :tasks
  mount_uploader :image, ImageUploader
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[ show edit update destroy ]

  # GET /pets or /pets.json
  def index
    @pets = Pet.all
    date_format = "%Y%m%d"
    @pets.each do |pet|
    @age = (Date.today.strftime(date_format).to_i - pet.birthday.strftime(date_format).to_i)/10000
    end
  end

  # GET /pets/1 or /pets/1.json
  def show
    date_format = "%Y%m%d"
    @age = (Date.today.strftime(date_format).to_i - @pet.birthday.strftime(date_format).to_i)/10000
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets or /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully created." }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1 or /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully updated." }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1 or /pets/1.json
  def destroy
    @pet.destroy

    respond_to do |format|
      format.html { redirect_to pets_url, notice: "Pet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_params
      params.require(:pet).permit(:name, :content, :family_id, :birthday)
    end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<%= form_with(model: pet) do |form| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
        <% pet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :名前 %><br>
    <%= form.text_field :name %>
  </div>

  <div class="title">
    <div class="form-tag">誕生日</div>
    <%= form.date_field :birthday %>
  </div>

  <div class="field">
    <%= form.label :備考欄 %><br>
    <%= form.text_area :content %>
  </div>

  <%= form.hidden_field :family_id, :value => current_user.families.first.id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<div class="container">
<h1>愛犬一覧</h1>
<%= link_to '愛犬を登録', new_pet_path %>
<hr />
  <div class="row">
    <div class="col-3">
    <h5>愛犬一覧</h5>
    <hr />
    <% @pets.each do |pet| %>
      <% if pet.family.id == current_user.families.first.id %>
        <li><%= link_to pet.name, pet %></li><br>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pets/new.html.erb
<h1>愛犬を登録</h1>
<hr />
<div class="col-md-3">
    <%= render 'form', pet: @pet %>

    <%= link_to 'Back', pets_path %>
</div>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>
<div class="col-3">
  <p>
    <strong>名前:</strong>
    <%= @pet.name %>
  </p>

  <p>
    <strong>年齢:</strong>
    <%= @age %>歳
  </p>

  <p>
    <strong>年齢:</strong>
    <%= @pet.birthday %>
  </p>
  <p>
    <strong>備考欄:</strong>
    <%= @pet.content %>
  </p>
</div>
<%= link_to 'Back', pets_path %>|
<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Destroy', @pet, method: :delete, data: { confirm: 'Are you sure?' } %>