config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {
    invitations: 'users/invitations'
  }
  resources :users, only: :show
  
  resources :healths
  resources :pets
  resources :families
  resources :tasks
  
  root to: "healths#index"
  
  
  post '/tasks/:id/done' => 'tasks#done',   as: 'done'
  get 'search' => 'healths#search'

end

app/models/family.rb
class Family < ApplicationRecord
    validates :name, presence: true
    has_many :groups, dependent: :destroy
    has_many :users, through: :groups, source: :user
    has_many :pets
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :set_family, only: %i[ show edit update destroy ]

  # GET /families or /families.json
  def index
    @families = Family.all
    @family = current_user.families.first
  end

  # GET /families/1 or /families/1.json
  def show
  end

  # GET /families/new
  def new
    @family = Family.new
  end

  # GET /families/1/edit
  def edit
  end

  # POST /families or /families.json
  # def create
  #   current_user.families.build(family_params)
  #   if current_user.save
  #     redirect_to user_path(current_user), notice: "作成しました"
  #   else
  #     render 'new'
  #   end
  # end

  def create
    family = Family.new(family_params)
    family.save
    group = Group.new
    group.user_id = current_user.id
    group.family_id = Family.last.id
    if group.save
      redirect_to user_path(current_user), notice: "作成しました"
    end
  end

  # PATCH/PUT /families/1 or /families/1.json
  def update
    respond_to do |format|
      if @family.update(family_params)
        format.html { redirect_to family_url(@family), notice: "Family was successfully updated." }
        format.json { render :show, status: :ok, location: @family }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /families/1 or /families/1.json
  def destroy
    @family.destroy

    respond_to do |format|
      format.html { redirect_to families_url, notice: "Family was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family
      @family = Family.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def family_params
      params.require(:family).permit(:name)
    end
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/views/families/_form.html.erb
<%= form_with(model: family) do |form| %>
  <% if family.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(family.errors.count, "error") %> prohibited this family from being saved:</h2>

      <ul>
        <% family.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/families/edit.html.erb
<h1>Editing Family</h1>

<%= render 'form', family: @family %>

<%= link_to 'Show', @family %> |
<%= link_to 'Back', families_path %>

app/views/families/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h2><%= @family.name %>ファミリー一覧</h2>
<hr />
  <div class="row">
    <div class="col-3">
    <h5>所属者名</h5>
    <hr />
      <% @family.users.each do |user| %>
        <li><%= user.name %></li><br>
      <% end %>
    </div>
    <div class="col-3">
    <h5>所属ペット</h5>
    <hr />
      <% @family.pets.each do |pet| %>
        <li><%= pet.name %></li><br>
      <% end %>
    </div>
  </div>
</div>

app/views/families/new.html.erb
<h2>家族登録</h2>
<hr />
<div class="col-3">
<%= render 'form', family: @family %>

<%= link_to 'Back', families_path %>

app/views/families/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @family.name %>
</p>

<%= link_to 'Edit', edit_family_path(@family) %> |
<%= link_to 'Back', families_path %>